# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
  pull_request:
    branches: [ "main", "test" ]

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:14
        ports: [5432:5432]
        env:
          POSTGRES_USER: testuser
          POSTGRES_PASSWORD: testpass
          POSTGRES_DB: testdb
        options: >-
          --health-cmd="pg_isready"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    env:
      DATABASE_URL: postgresql://testuser:testpass@localhost:5432/provision_it_v2
      TEST_DATABASE_URL: postgresql://testuser:testpass@localhost:5432/provision_it_v2_test
      SECRET_KEY: test-secret-key-for-ci
      FLASK_ENV: testing

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install Node.js dependencies for E2E tests
        run: |
          cd test/tests/E2E
          npm install

      - name: Install Playwright browsers
        run: |
          cd test/tests/E2E
          npx playwright install chromium --with-deps

      - name: Set up test database
        run: |
          python test/test_database/manage_test_db.py full-setup

      - name: Run unit tests
        run: |
          pytest test/tests/unit/ -v --cov=app --cov-report=term-missing --cov-report=html:htmlcov --cov-report=xml:coverage.xml --cov-fail-under=40 --tb=short --maxfail=3

      - name: Run database tests
        run: |
          pytest test/tests/infrastructure/test_db.py test/tests/infrastructure/test_database_setup.py -v --tb=short --maxfail=3

      - name: Run integration tests
        run: |
          pytest test/tests/integration/ -v --tb=short --maxfail=3

      - name: Install frontend test dependencies
        run: |
          cd test/tests/Jest
          npm install

      - name: Run frontend unit tests (Jest)
        run: |
          cd test/tests/Jest
          npm test

      - name: Start Flask server for E2E tests
        env:
          FLASK_HOST: 0.0.0.0
          FLASK_PORT: 5001
        run: |
          python run.py &
          sleep 10
          curl -f http://localhost:5001/health || exit 1

      - name: Run E2E tests
        run: |
          cd test/tests/E2E
          npm test