name: Run Tests

on: 
  push:
    branches: [ main, develop, test ]
  pull_request:
    branches: [ main, develop ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_USER: testuser
          POSTGRES_PASSWORD: testpass
          POSTGRES_DB: provision_it_test
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        
    - name: Cache pip dependencies
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
          
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Set up test database
      run: |
        # Wait for PostgreSQL to be ready
        until pg_isready -h localhost -p 5432 -U testuser; do
          echo "Waiting for PostgreSQL..."
          sleep 2
        done
        
        # Create test database if it doesn't exist
        PGPASSWORD=testpass psql -h localhost -U testuser -d postgres -c "CREATE DATABASE provision_it_test;" || true
        
    - name: Run unit tests
      env:
        DATABASE_URL: postgresql://testuser:testpass@localhost/provision_it_test
        FLASK_ENV: testing
      run: |
        python run_tests.py --unit --coverage --verbose
        
    - name: Run database tests
      env:
        DATABASE_URL: postgresql://testuser:testpass@localhost/provision_it_test
        FLASK_ENV: testing
      run: |
        python run_tests.py --database --coverage --verbose
        
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        file: ./coverage.xml
        flags: unittests
        name: codecov-umbrella
        fail_ci_if_error: false
        
    - name: Archive test results
      uses: actions/upload-artifact@v3
      if: always()
      with:
        name: test-results
        path: |
          coverage.xml
          htmlcov/
          .coverage
          
    - name: Comment PR with coverage
      if: github.event_name == 'pull_request'
      uses: py-cov-action@v1.0.3
      with:
        path: coverage.xml
        title: 'Coverage Report'
        fail_below_threshold: true
        threshold: 80